on: [push, pull_request]
name: Format
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add Tool
      run: rustup component add rustfmt
    - name: Check Format
      run: cargo fmt -- --check
